services:
  spark:
    image: apache/spark:3.5.0  # <-- Imagen oficial de Apache, esta sí o sí existe
    container_name: spark
    user: "0:0"
    stdin_open: true
    tty: true
    # El comando cambia ligeramente porque en la imagen oficial la ruta es /opt/spark
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "0.0.0.0"]
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: "0.0.0.0"
      SPARK_LOCAL_IP: "127.0.0.1"
    volumes:
      - ./data:/opt/spark-data