version: "3.8"

services:
  kafka-nodo:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-cluster-nodo-${NODO_ID}
    env_file:
      - .env
    restart: unless-stopped
    network_mode: "host"

    environment:
      # Identidad del nodo
      KAFKA_NODE_ID: ${NODO_ID}
      KAFKA_PROCESS_ROLES: "broker,controller"

      # Cluster KRaft de 3 nodos
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@100.115.62.37:9093,2@100.123.126.75:9093,3@100.72.209.77:9093"

      # Listeners
      # 9092 = comunicación entre brokers y clientes Python
      # 9093 = comunicación interna de controllers KRaft
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${LAPTOP_IP}:9092"

      # Seguridad simple para red local/Tailscale
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

      # Configuración KRaft
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Mismo CLUSTER_ID en los 3 nodos
      CLUSTER_ID: "4L62YDgNTki3A6wV3lExlw=="
      KAFKA_CLUSTER_ID: "4L62YDgNTki3A6wV3lExlw=="

      # Configuración de replicación interna
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Configuración general
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Directorio de datos
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"

      # Logs menos ruidosos
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.server=INFO,org.apache.kafka=WARN"

    volumes:
      - kafka-data:/var/lib/kafka/data

volumes:
  kafka-data: