services:
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master-nodo-3
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"   # Puerto interno de comunicación
      - "8080:8080"   # Interfaz Web para el Dr. Galván
    volumes:
      - ../shared-data:/opt/spark/shared-data
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge