services:
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master-nodo-3
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ../shared-data:/opt/spark/shared-data
    networks:
      - spark-net
    # AQUÍ ESTÁ LA CORRECCIÓN: Le decimos a Apache Spark que arranque como master
    command: /opt/spark/sbin/start-master.sh

networks:
  spark-net:
    driver: bridge