services:
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker-nodo
    user: root  # Evita bloqueos de permisos en sus laptops
    environment:
      - SPARK_MODE=worker
    ports:
      - "8081:8081"
    volumes:
      - ../shared-data:/opt/spark/shared-data
    networks:
      - spark-net
    # CONEXIÓN DIRECTA EN TIEMPO REAL:
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://192.168.0.103:7077

networks:
  spark-net:
    driver: bridge