services:
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker-nodo
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://192.168.0.103:7077
    volumes:
      - ../shared-data:/opt/spark/shared-data
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge